dist: xenial   # required for Python >= 3.7
language: python
sudo: required

services:
  - postgresql
addons:
  postgresql: "11.3"

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log

python:
  # - "3.6"
  - "3.7"

before_install:
  - pip3 install --upgrade pip

install:
  - pip3 install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE pmr"
  - psql -c "CREATE USER admin WITH PASSWORD 'admin'"
  - psql -c "ALTER ROLE admin SET client_encoding TO 'utf8'"
  - psql -c "ALTER ROLE admin SET default_transaction_isolation TO 'read committed'"
  - psql -c "ALTER ROLE admin SET timezone TO 'UTC'"
  - psql -c "ALTER USER admin CREATEDB"
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - flake8 .
  - coverage run --source='.'  manage.py test

after_success:
  - coveralls